version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: macbeth
      POSTGRES_PASSWORD: pass12345
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5438:5432
    volumes:
      - ./.db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
